/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2021-04-16 05:48:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pur;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<h2>[🗳구매목록🗳]</h2>\r\n");
      out.write("<div id=\"divCondition\">\r\n");
      out.write("   <div style=\"float:left;\">\r\n");
      out.write("      <select id=\"key\">\r\n");
      out.write("         <option value=\"order_id\">구매코드</option>\r\n");
      out.write("         <option value=\"name\">구매자이름</option>\r\n");
      out.write("         <option value=\"address\">구매자주소</option>\r\n");
      out.write("         <option value=\"tel\">전화</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <input type=\"text\" id=\"word\" placeholder=\"검색어\"/>\r\n");
      out.write("      <select id=\"perpage\">\r\n");
      out.write("         <option value=\"3\">3개씩출력</option>\r\n");
      out.write("         <option value=\"6\">6개씩출력</option>\r\n");
      out.write("         <option value=\"9\">9개씩출력</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <span id=\"count\"></span>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div style=\"float:right\">\r\n");
      out.write("      <select id=\"order\">\r\n");
      out.write("         <option value=\"order_id\">구매코드</option>\r\n");
      out.write("         <option value=\"name\">구매자이름</option>\r\n");
      out.write("         <option value=\"address\">구매자주소</option>\r\n");
      out.write("         <option value=\"tel\">전화</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <select id=\"desc\">\r\n");
      out.write("         <option value=\"desc\">내림차순</option>\r\n");
      out.write("         <option value=\"asc\">오름차순</option>\r\n");
      out.write("      </select>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<table id=\"tbl\"></table>\r\n");
      out.write("<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("<tr class=\"title\">\r\n");
      out.write("   <td width=100>구매코드</td>\r\n");
      out.write("   <td width=100>구매자이름</td>\r\n");
      out.write("   <td width=300>구매자 주소</td>\r\n");
      out.write("   <td width=100>구매자 전화</td>\r\n");
      out.write("   <td width=150>구매정보</td>\r\n");
      out.write("</tr>\r\n");
      out.write("{{#each array}}\r\n");
      out.write("<tr class=\"row\" pdate=\"{{pdate}}\" paytype=\"{{paytype}}\" email=\"{{email}}\" status=\"{{status}}\">\r\n");
      out.write("   <td class=\"order_id\">{{order_id}}</td>\r\n");
      out.write("   <td class=\"name\">{{name}}</td>\r\n");
      out.write("   <td class=\"address\">{{address}}</td>\r\n");
      out.write("   <td class=\"tel\">{{tel}}</td>\r\n");
      out.write("   <td><button style=\"text-align:center\">구매정보</button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"pagination\">\r\n");
      out.write("   <button id=\"btnPre\">이전</button>\r\n");
      out.write("   <span id=\"pageInfo\"></span>\r\n");
      out.write("   <button id=\"btnNext\">다음</button>\r\n");
      out.write("</div>\r\n");
      out.write("<table id=\"tbl1\" style=\"margin-top:20px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"title\" width=100>이름</td>\r\n");
      out.write("\t\t<td class=\"name\" width=100></td>\r\n");
      out.write("\t\t<td class=\"title\" width=100>전화</td>\r\n");
      out.write("\t\t<td class=\"tel\" width=200></td>\r\n");
      out.write("\t\t<td class=\"title\" width=50>이메일</td>\r\n");
      out.write("\t\t<td class=\"email\" width=150></td>\r\n");
      out.write("\t\t<td class=\"title\" width=100>구매일</td>\r\n");
      out.write("\t\t<td class=\"pdate\" width=250></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"title\" width=200>주소</td>\r\n");
      out.write("\t\t<td class=\"address\" colspan=\"3\"></td>\r\n");
      out.write("\t\t<td class=\"title\" width=50>결제</td>\r\n");
      out.write("\t\t<td class=\"paytype\" width=150></td>\r\n");
      out.write("\t\t<td class=\"title\" width=100>배송상태</td>\r\n");
      out.write("\t\t<td class=\"status\" width=200></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!-- 구매상품목록 -->\r\n");
      out.write("<table id=\"tbl2\"></table>\r\n");
      out.write("<script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t<tr class=\"title\">\r\n");
      out.write("\t\t<td width=100>상품번호</td>\r\n");
      out.write("\t\t<td width=300>상품이름</td>\r\n");
      out.write("\t\t<td width=100>상품가격</td>\r\n");
      out.write("\t\t<td width=100>상품수량</td>\r\n");
      out.write("\t\t<td width=100>상품금액</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t{{#each .}}\r\n");
      out.write("\t<tr class=\"row\">\r\n");
      out.write("\t\t<td>{{prod_id}}</td>\r\n");
      out.write("\t\t<td>{{prod_name}}</td>\r\n");
      out.write("\t\t<td style=\"text-align:right\">{{nf price}}</td>\r\n");
      out.write("\t\t<td style=\"text-align:right\">{{nf quantity}}</td>\r\n");
      out.write("\t\t<td style=\"text-align:right\">{{nf sum}}</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("Handlebars.registerHelper(\"nf\", function(price1){\r\n");
      out.write("\tvar regexp= /\\B(?=(\\d{3})+(?!\\d))/g;\r\n");
      out.write("\treturn price1.toString().replace(regexp, \",\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("   var url=\"/pur/list.json\";\r\n");
      out.write("   $(\"#tbl1\").hide();\r\n");
      out.write("   \r\n");
      out.write("   $(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t   $(\"#tbl1\").show();\r\n");
      out.write("\t   var row=$(this).parent().parent();\r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#tbl1 .name\").html(row.find(\".name\").html());\r\n");
      out.write("\t   $(\"#tbl1 .tel\").html(row.find(\".tel\").html());\r\n");
      out.write("\t   $(\"#tbl1 .email\").html(row.attr(\"email\"));\r\n");
      out.write("\t   $(\"#tbl1 .pdate\").html(row.attr(\"pdate\"));\r\n");
      out.write("\t   $(\"#tbl1 .address\").html(row.find(\".address\").html());\r\n");
      out.write("\t   \r\n");
      out.write("\t   var paytype=row.attr(\"paytype\")==\"0\" ? \"현금\":\"카드\";\r\n");
      out.write("\t   $(\"#tbl1 .paytype\").html(paytype);\r\n");
      out.write("\t   var status=row.attr(\"status\")==\"0\" ? \"처리중\":\"처리완료\";\r\n");
      out.write("\t   $(\"#tbl1 .status\").html(status);\r\n");
      out.write("\t   \r\n");
      out.write("\t   //구매상품목록출력\r\n");
      out.write("\t   var order_id=row.find(\".order_id\").html();\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t   type:\"get\",\r\n");
      out.write("\t\t   url:\"/pur/plist.json\",\r\n");
      out.write("\t\t   data:{\"order_id\":order_id},\r\n");
      out.write("\t\t   dataType:\"json\",\r\n");
      out.write("\t\t   success:function(result){\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl2\").html(temp(result));\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   });\r\n");
      out.write("\t   \r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/script.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
